menuGradients:
  nameTop: "#F46B45"
  nameBottom: "#EEA849"
  firstItemTop: "#FDFC47"
  firstItemBottom: "#24FE41"
  secondItemTop: "#FC00FF"
  secondItemBottom: "#00DBDE"
  thirdItemTop: "#005C97"
  thirdItemBottom: "#363795"
