name: InviteManager
version: ${project.version}
main: com.gonagutor.invitemanager.InviteManager
api-version: 1.16
authors: [GonzaloAguadoTorres]
softdepend: [PlaceholderAPI]
description: This plguins let players invite other players and prevent uninvited players to do anything
commands:
  vengode:
    description: Este comando sirve para identificarte al entrar al server por primera vez
    usage: /<command> [codigo]
    permission: InviteManager.vengode
  invitar:
    description: Este comando sirve para crear un codigo de invitación a tu nombre
    usage: /<command>
    permission: InviteManager.invitar
  im:
    description: Este comando muestra los comandos de admin
    usage: /<command> [comando] [comando] [comando] [comando] [comando] [comando]
    permissions: InviteManager.admin
